/*===============================================
                    Site
===============================================*/

/*=============================
           Variables
=============================*/
/** ID Generated by the server to define the Client. */
var clientId;

/*=============================
           Events
=============================*/
/** Load event to populate the clientId if not populated yet.
 */
$(window).load(function () {
    if (!Exists(localStorage.getItem("clientId")))
        GetClientId();
    clientId = localStorage.getItem("clientId");
})

/*=============================
           Methods
=============================*/
/** Checks if a given value exists.
 *  Parameters:
 *   value: The value to check.
 *  Returns: True if exists and false otherwise.
 */
function Exists(value) {
    return !(value == null || value == '' || value.length == null || value.length <= 0);
}

/** Fills the clientId field with a newly
 *  generated Guid from the server.
 */
function GetClientId() {
    $.get({
        url: '/ClientInformationAjax/GenerateClientId',
        dataType: 'json',
        async: true
    }).success(function (data) {
        localStorage.setItem("clientId", data.clientId);
    });
}