/**
 * @file Provides global functionalities to all pages across the website.
 * @author Joshua Morgan
 * @since 1.0.0.0
 */

/*=============================
           Variables
=============================*/
/**
 * ID Generated by the server to define the Client.
 * @type {guid}
 * @global
 */
var clientId;
/**
 * Label for the clientId field in localStorage.
 * @type {string}
 * @global
 * @readonly
 */
var clientIdLabel = 'clientId';

/*=============================
           Events
=============================*/
/**
 * Load event to populate the clientId if not populated yet.
 * @listens module:window~event:load
 */
$(window).load(function () {
    if (!Exists(localStorage.getItem(clientIdLabel))) {
        GetClientId();
        clientId = localStorage.getItem(clientIdLabel);
    } else if (!Exists(clientId))
        clientId = localStorage.getItem(clientIdLabel);
});

/*=============================
           Methods
=============================*/
/**
 * @function Exists
 * @description Checks if a given value exists.
 * @param value - The value to check.
 * @returns {boolean} True/False if the provided value exists
 */
function Exists(value) {
    return !(value === null || value === '' || value.length === null || value.length <= 0);
}

/**
 * @function GetClientId
 * @description Fills the localStorage 'clientId' field with a newly generated
 * GUID from the server.
 * @summary Gets a GUID from the server.
 */
function GetClientId() {
    $.get({
        url: '/ClientInformationAjax/GenerateClientId',
        dataType: 'json',
        async: true
    }).success(function (data) {
        localStorage.setItem(clientIdLabel, data.clientId);
    });
}